### ISSUE TITLE
Allow rails version 8

### ISSUE THREAD

**Issue by bendangelo** [rkwap/active_storage_bunny#1]
https://github.com/rkwap/active_storage_bunny/blob/main/active_storage_bunny.gemspec#L22

**Comment by rkwap** [comment]
@bendangelo I don't have time to test it for rails 8 for quite sometime. It would be quite helpful if you can test it and I will surely update gemspec.

**Comment by bendangelo** [comment]
ok I'll test it out.

**Comment by bendangelo** [comment]
I opened a PR, added more than I thought. https://github.com/rkwap/active_storage_bunny/pull/2
